from typing import Any, Protocol
from harness.contracts import Checkpoint, HarnessRun, ModelRequest, ModelResponse, RunState
from .versioning import RevisionGuard, VersionedRead, VersionedReadSet

class RuntimePort(Protocol):
    def execute(self, run: HarnessRun, payload: dict[str, Any]) -> RunState: ...
    def resume(self, run: HarnessRun, state: RunState) -> RunState: ...
class ModelPort(Protocol):
    def invoke(self, request: ModelRequest) -> ModelResponse: ...
class ToolPort(Protocol):
    def invoke(self, tool_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
class MemoryPort(Protocol):
    def retrieve(self, request: dict[str, Any]) -> dict[str, Any]: ...
class WorkspacePort(Protocol):
    def resolve(self, workspace_ref: str) -> str: ...
class SourcePort(Protocol):
    def read(self, source_ref: str) -> dict[str, Any]: ...
    def read_versioned(self, source_ref: str) -> VersionedRead: ...
    def acquire_revision_guard(self, expected_versions: VersionedReadSet, owner_ref: str) -> RevisionGuard: ...
    def release_revision_guard(self, guard: RevisionGuard) -> None: ...
class StatePort(Protocol):
    def save_run_state(self, state: RunState) -> None: ...
    def load_run_state(self, run_state_id: str) -> RunState: ...
    def save_checkpoint(self, checkpoint: Checkpoint) -> None: ...
    def load_checkpoint(self, checkpoint_id: str) -> Checkpoint: ...
    def save_revalidation_record(self, revalidation_id: str, record: dict[str, Any]) -> None: ...
    def load_revalidation_record(self, revalidation_id: str) -> dict[str, Any]: ...
    def list_revalidation_records(self, run_id: str) -> list[dict[str, Any]]: ...
    def create_idempotency_record(self, key: str, record: dict[str, Any]) -> bool: ...
    def load_idempotency_record(self, key: str) -> dict[str, Any]: ...
    def update_idempotency_record(self, key: str, record: dict[str, Any]) -> None: ...
    def compare_and_swap_idempotency_record(
        self,
        key: str,
        expected: dict[str, Any],
        replacement: dict[str, Any],
    ) -> bool: ...

__all__ = [
    "MemoryPort",
    "ModelPort",
    "RevisionGuard",
    "RuntimePort",
    "SourcePort",
    "StatePort",
    "ToolPort",
    "VersionedRead",
    "VersionedReadSet",
    "WorkspacePort",
]
