from typing import Any, Protocol
from harness.contracts import HarnessRun, RunState

class RuntimePort(Protocol):
    def execute(self, run: HarnessRun, payload: dict[str, Any]) -> RunState: ...
    def resume(self, run: HarnessRun, state: RunState) -> RunState: ...
class ModelPort(Protocol):
    def invoke(self, request: dict[str, Any]) -> dict[str, Any]: ...
class ToolPort(Protocol):
    def invoke(self, tool_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
class MemoryPort(Protocol):
    def retrieve(self, request: dict[str, Any]) -> dict[str, Any]: ...
class WorkspacePort(Protocol):
    def resolve(self, workspace_ref: str) -> str: ...
class SourcePort(Protocol):
    def read(self, source_ref: str) -> dict[str, Any]: ...
